name: uic
description: A set of high-level Flutter UI components and stand-alone widgets that helps building your app.
version: 0.11.0
homepage: https://github.com/echedev/uic-flutter
repository: https://github.com/echedev/uic-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
